# Site settings
course_name: Natural Language Processing
course_description: "Design of natural language processing systems; part-of speech tagging, statistical and symbolic parsers; semantic interpretation; discourse and dialogue processing; natural language generation; applications."
course_semester: "Fall 2025"

# GitHub Pages config (project site)
url: "https://rohancsalvi.github.io"          # ← domain ONLY
baseurl: "/uic_cs_421.github.io"              # ← repo name with leading slash

schoolname: "UIC"
schoolurl: "https://uic.edu"

address: |
  Department of Computer Science
  University of Illinois, Chicago
  USA

# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
  events:
    output: true
  lectures:
    output: true
  assignments:
    output: true
  announcements:
    output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
